from multiprocessing import Condition
from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd #dataframe
import numpy as np #mathematical computations
import xgboost
import pickle
app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}



class Item(BaseModel):
    
    region:str 
    title_status:str
    condition:str
    age:int
    manufacturer:str
    model:str
    cylinders:str
    fuel:str
    odometer:int
    transmission:str
    drive:str
    cartype:str
    paint_color:str
    n_sold:int


@app.post('/price/')
async def get_price(body: Item):

    
    region_dict = {'SF bay area': 0,
                     'abilene': 1,
                     'akron / canton': 2,
                     'albany': 3,
                     'albuquerque': 4,
                     'altoona-johnstown': 5,
                     'amarillo': 6,
                     'ames': 7,
                     'anchorage / mat-su': 8,
                     'ann arbor': 9,
                     'annapolis': 10,
                     'appleton-oshkosh-FDL': 11,
                     'asheville': 12,
                     'ashtabula': 13,
                     'athens': 14,
                     'atlanta': 15,
                     'auburn': 16,
                     'augusta': 17,
                     'austin': 18,
                     'bakersfield': 19,
                     'baltimore': 20,
                     'baton rouge': 21,
                     'battle creek': 22,
                     'beaumont / port arthur': 23,
                     'bellingham': 24,
                     'bemidji': 25,
                     'bend': 26,
                     'billings': 27,
                     'binghamton': 28,
                     'birmingham': 29,
                     'bismarck': 30,
                     'bloomington': 31,
                     'bloomington-normal': 32,
                     'boise': 33,
                     'boone': 34,
                     'boston': 35,
                     'boulder': 36,
                     'bowling green': 37,
                     'bozeman': 38,
                     'brainerd': 39,
                     'brownsville': 40,
                     'brunswick': 41,
                     'buffalo': 42,
                     'butte': 43,
                     'cape cod / islands': 44,
                     'catskills': 45,
                     'cedar rapids': 46,
                     'central NJ': 47,
                     'central louisiana': 48,
                     'central michigan': 49,
                     'champaign urbana': 50,
                     'charleston': 51,
                     'charlotte': 52,
                     'charlottesville': 53,
                     'chattanooga': 54,
                     'chautauqua': 55,
                     'chicago': 56,
                     'chico': 57,
                     'chillicothe': 58,
                     'cincinnati': 59,
                     'clarksville': 60,
                     'cleveland': 61,
                     'clovis / portales': 62,
                     'college station': 63,
                     'colorado springs': 64,
                     'columbia': 65,
                     'columbia / jeff city': 66,
                     'columbus': 67,
                     'cookeville': 68,
                     'corpus christi': 69,
                     'corvallis/albany': 70,
                     'cumberland valley': 71,
                     'dallas / fort worth': 72,
                     'danville': 73,
                     'dayton / springfield': 74,
                     'daytona beach': 75,
                     'decatur': 76,
                     'deep east texas': 77,
                     'del rio / eagle pass': 78,
                     'delaware': 79,
                     'denver': 80,
                     'des moines': 81,
                     'detroit metro': 82,
                     'dothan': 83,
                     'dubuque': 84,
                     'duluth / superior': 85,
                     'east idaho': 86,
                     'east oregon': 87,
                     'eastern CO': 88,
                     'eastern CT': 89,
                     'eastern NC': 90,
                     'eastern kentucky': 91,
                     'eastern montana': 92,
                     'eastern panhandle': 93,
                     'eastern shore': 94,
                     'eau claire': 95,
                     'el paso': 96,
                     'elko': 97,
                     'elmira-corning': 98,
                     'erie': 99,
                     'eugene': 100,
                     'evansville': 101,
                     'fairbanks': 102,
                     'fargo / moorhead': 103,
                     'farmington': 104,
                     'fayetteville': 105,
                     'finger lakes': 106,
                     'flagstaff / sedona': 107,
                     'flint': 108,
                     'florence': 109,
                     'florence / muscle shoals': 110,
                     'florida keys': 111,
                     'fort collins / north CO': 112,
                     'fort dodge': 113,
                     'fort smith': 114,
                     'fort wayne': 115,
                     'frederick': 116,
                     'fredericksburg': 117,
                     'fresno / madera': 118,
                     'ft myers / SW florida': 119,
                     'gadsden-anniston': 120,
                     'gainesville': 121,
                     'galveston': 122,
                     'glens falls': 123,
                     'gold country': 124,
                     'grand forks': 125,
                     'grand island': 126,
                     'grand rapids': 127,
                     'great falls': 128,
                     'green bay': 129,
                     'greensboro': 130,
                     'greenville / upstate': 131,
                     'gulfport / biloxi': 132,
                     'hanford-corcoran': 133,
                     'harrisburg': 134,
                     'harrisonburg': 135,
                     'hartford': 136,
                     'hattiesburg': 137,
                     'hawaii': 138,
                     'heartland florida': 139,
                     'helena': 140,
                     'hickory / lenoir': 141,
                     'high rockies': 142,
                     'hilton head': 143,
                     'holland': 144,
                     'houma': 145,
                     'houston': 146,
                     'hudson valley': 147,
                     'humboldt county': 148,
                     'huntington-ashland': 149,
                     'huntsville / decatur': 150,
                     'imperial county': 151,
                     'indianapolis': 152,
                     'inland empire': 153,
                     'iowa city': 154,
                     'ithaca': 155,
                     'jackson': 156,
                     'jacksonville': 157,
                     'janesville': 158,
                     'jersey shore': 159,
                     'jonesboro': 160,
                     'joplin': 161,
                     'kalamazoo': 162,
                     'kalispell': 163,
                     'kansas city, MO': 164,
                     'kenai peninsula': 165,
                     'kennewick-pasco-richland': 166,
                     'kenosha-racine': 167,
                     'killeen / temple / ft hood': 168,
                     'kirksville': 169,
                     'klamath falls': 170,
                     'knoxville': 171,
                     'kokomo': 172,
                     'la crosse': 173,
                     'la salle co': 174,
                     'lafayette': 175,
                     'lafayette / west lafayette': 176,
                     'lake charles': 177,
                     'lake of the ozarks': 178,
                     'lakeland': 179,
                     'lancaster': 180,
                     'lansing': 181,
                     'laredo': 182,
                     'las cruces': 183,
                     'las vegas': 184,
                     'lawrence': 185,
                     'lawton': 186,
                     'lehigh valley': 187,
                     'lewiston / clarkston': 188,
                     'lexington': 189,
                     'lima / findlay': 190,
                     'lincoln': 191,
                     'little rock': 192,
                     'logan': 193,
                     'long island': 194,
                     'los angeles': 195,
                     'louisville': 196,
                     'lubbock': 197,
                     'lynchburg': 198,
                     'macon / warner robins': 199,
                     'madison': 200,
                     'maine': 201,
                     'manhattan': 202,
                     'mankato': 203,
                     'mansfield': 204,
                     'mason city': 205,
                     'mattoon-charleston': 206,
                     'mcallen / edinburg': 207,
                     'meadville': 208,
                     'medford-ashland': 209,
                     'memphis': 210,
                     'mendocino county': 211,
                     'merced': 212,
                     'meridian': 213,
                     'milwaukee': 214,
                     'minneapolis / st paul': 215,
                     'missoula': 216,
                     'mobile': 217,
                     'modesto': 218,
                     'mohave county': 219,
                     'monroe': 220,
                     'monterey bay': 221,
                     'montgomery': 222,
                     'morgantown': 223,
                     'moses lake': 224,
                     'muncie / anderson': 225,
                     'muskegon': 226,
                     'myrtle beach': 227,
                     'nashville': 228,
                     'new hampshire': 229,
                     'new haven': 230,
                     'new orleans': 231,
                     'new river valley': 232,
                     'new york city': 233,
                     'norfolk / hampton roads': 234,
                     'north central FL': 235,
                     'north dakota': 236,
                     'north jersey': 237,
                     'north mississippi': 238,
                     'north platte': 239,
                     'northeast SD': 240,
                     'northern WI': 241,
                     'northern michigan': 242,
                     'northern panhandle': 243,
                     'northwest CT': 244,
                     'northwest GA': 245,
                     'northwest KS': 246,
                     'northwest OK': 247,
                     'ocala': 248,
                     'odessa / midland': 249,
                     'ogden-clearfield': 250,
                     'okaloosa / walton': 251,
                     'oklahoma city': 252,
                     'olympic peninsula': 253,
                     'omaha / council bluffs': 254,
                     'oneonta': 255,
                     'orange county': 256,
                     'oregon coast': 257,
                     'orlando': 258,
                     'outer banks': 259,
                     'owensboro': 260,
                     'palm springs': 261,
                     'panama city': 262,
                     'parkersburg-marietta': 263,
                     'pensacola': 264,
                     'peoria': 265,
                     'philadelphia': 266,
                     'phoenix': 267,
                     'pierre / central SD': 268,
                     'pittsburgh': 269,
                     'plattsburgh-adirondacks': 270,
                     'poconos': 271,
                     'port huron': 272,
                     'portland': 273,
                     'potsdam-canton-massena': 274,
                     'prescott': 275,
                     'provo / orem': 276,
                     'pueblo': 277,
                     'pullman / moscow': 278,
                     'quad cities, IA/IL': 279,
                     'raleigh / durham / CH': 280,
                     'rapid city / west SD': 281,
                     'reading': 282,
                     'redding': 283,
                     'reno / tahoe': 284,
                     'rhode island': 285,
                     'richmond': 286,
                     'roanoke': 287,
                     'rochester': 288,
                     'rockford': 289,
                     'roseburg': 290,
                     'roswell / carlsbad': 291,
                     'sacramento': 292,
                     'saginaw-midland-baycity': 293,
                     'salem': 294,
                     'salina': 295,
                     'salt lake city': 296,
                     'san angelo': 297,
                     'san antonio': 298,
                     'san diego': 299,
                     'san luis obispo': 300,
                     'san marcos': 301,
                     'sandusky': 302,
                     'santa barbara': 303,
                     'santa fe / taos': 304,
                     'santa maria': 305,
                     'sarasota-bradenton': 306,
                     'savannah / hinesville': 307,
                     'scottsbluff / panhandle': 308,
                     'scranton / wilkes-barre': 309,
                     'seattle-tacoma': 310,
                     'sheboygan': 311,
                     'show low': 312,
                     'shreveport': 313,
                     'sierra vista': 314,
                     'sioux city': 315,
                     'sioux falls / SE SD': 316,
                     'siskiyou county': 317,
                     'skagit / island / SJI': 318,
                     'south bend / michiana': 319,
                     'south coast': 320,
                     'south dakota': 321,
                     'south florida': 322,
                     'south jersey': 323,
                     'southeast IA': 324,
                     'southeast KS': 325,
                     'southeast alaska': 326,
                     'southeast missouri': 327,
                     'southern WV': 328,
                     'southern illinois': 329,
                     'southern maryland': 330,
                     'southwest KS': 331,
                     'southwest MN': 332,
                     'southwest VA': 333,
                     'southwest michigan': 334,
                     'space coast': 335,
                     "spokane / coeur d'alene": 336,
                     'springfield': 337,
                     'st augustine': 338,
                     'st cloud': 339,
                     'st george': 340,
                     'st joseph': 341,
                     'st louis': 342,
                     'st louis, MO': 343,
                     'state college': 344,
                     'statesboro': 345,
                     'stillwater': 346,
                     'stockton': 347,
                     'susanville': 348,
                     'syracuse': 349,
                     'tallahassee': 350,
                     'tampa bay area': 351,
                     'terre haute': 352,
                     'texarkana': 353,
                     'texoma': 354,
                     'the thumb': 355,
                     'toledo': 356,
                     'topeka': 357,
                     'treasure coast': 358,
                     'tri-cities': 359,
                     'tucson': 360,
                     'tulsa': 361,
                     'tuscaloosa': 362,
                     'tuscarawas co': 363,
                     'twin falls': 364,
                     'twin tiers NY/PA': 365,
                     'tyler / east TX': 366,
                     'upper peninsula': 367,
                     'utica-rome-oneida': 368,
                     'valdosta': 369,
                     'ventura county': 370,
                     'vermont': 371,
                     'victoria': 372,
                     'visalia-tulare': 373,
                     'waco': 374,
                     'washington, DC': 375,
                     'waterloo / cedar falls': 376,
                     'watertown': 377,
                     'wausau': 378,
                     'wenatchee': 379,
                     'west virginia (old)': 380,
                     'western IL': 381,
                     'western KY': 382,
                     'western maryland': 383,
                     'western massachusetts': 384,
                     'western slope': 385,
                     'wichita': 386,
                     'wichita falls': 387,
                     'williamsport': 388,
                     'wilmington': 389,
                     'winchester': 390,
                     'winston-salem': 391,
                     'worcester / central MA': 392,
                     'wyoming': 393,
                     'yakima': 394,
                     'york': 395,
                     'youngstown': 396,
                     'yuba-sutter': 397,
                     'yuma': 398,
                     'zanesville / cambridge': 399}
    title_status_dict = {'clean': 0,
                     'lien': 1,
                     'missing': 2,
                     'parts only': 3,
                     'rebuilt': 4,
                     'salvage': 5}
    model_dict = {'1500': 0,
                 '1500 crew cab big horn': 1,
                 '1500 quad cab harvest pickup': 2,
                 '200': 3,
                 '2500': 4,
                 '3': 5,
                 '300': 6,
                 '328i': 7,
                 '3500': 8,
                 '370z nismo coupe 2d': 9,
                 '4runner': 10,
                 'a4': 11,
                 'acadia': 12,
                 'accord': 13,
                 'altima': 14,
                 'camaro': 15,
                 'camaro ss coupe 2d': 16,
                 'camry': 17,
                 'camry le': 18,
                 'challenger r/t coupe 2d': 19,
                 'charger': 20,
                 'cherokee': 21,
                 'civic': 22,
                 'civic lx': 23,
                 'colorado': 24,
                 'colorado extended cab': 25,
                 'corolla': 26,
                 'corvette': 27,
                 'corvette grand sport': 28,
                 'cr-v': 29,
                 'cruze': 30,
                 'durango': 31,
                 'edge': 32,
                 'elantra': 33,
                 'enclave': 34,
                 'equinox': 35,
                 'escalade': 36,
                 'escape': 37,
                 'expedition': 38,
                 'expedition xlt sport': 39,
                 'explorer': 40,
                 'f-250': 41,
                 'f150': 42,
                 'f250 super duty': 43,
                 'fit': 44,
                 'focus': 45,
                 'focus se': 46,
                 'forester': 47,
                 'frontier': 48,
                 'frontier crew cab pro-4x': 49,
                 'fusion': 50,
                 'fusion se': 51,
                 'grand caravan': 52,
                 'grand cherokee': 53,
                 'highlander': 54,
                 'impala': 55,
                 'impreza': 56,
                 'jetta': 57,
                 'legacy': 58,
                 'liberty': 59,
                 'malibu': 60,
                 'maxima': 61,
                 'mdx': 62,
                 'mustang': 63,
                 'mustang gt coupe 2d': 64,
                 'odyssey': 65,
                 'optima': 66,
                 'outback': 67,
                 'passat': 68,
                 'pathfinder': 69,
                 'patriot': 70,
                 'pilot': 71,
                 'prius': 72,
                 'ranger': 73,
                 'rav4': 74,
                 'rogue': 75,
                 'rx 350': 76,
                 'santa fe': 77,
                 'sentra': 78,
                 'sienna': 79,
                 'sierra': 80,
                 'sierra 1500': 81,
                 'sierra 2500 hd double cab': 82,
                 'sierra 2500hd': 83,
                 'silverado': 84,
                 'silverado 1500 double': 85,
                 'silverado 1500 ld': 86,
                 'silverado 2500hd': 87,
                 'sonata': 88,
                 'soul': 89,
                 'suburban': 90,
                 'super duty f-250 srw': 91,
                 'super duty f-550 drw': 92,
                 'tacoma': 93,
                 'tacoma double cab pickup': 94,
                 'tahoe': 95,
                 'taurus': 96,
                 'town & country': 97,
                 'transit': 98,
                 'traverse': 99,
                 'tundra': 100,
                 'versa': 101,
                 'wrangler': 102,
                 'wrangler unlimited': 103,
                 'wrangler unlimited rubicon': 104,
                 'wrangler unlimited sport': 105,
                 'x5': 106,
                 'yukon': 107}
    manufacturer_dic = {'acura': 0,
                     'audi': 1,
                     'bmw': 2,
                     'buick': 3,
                     'cadillac': 4,
                     'chevrolet': 5,
                     'chrysler': 6,
                     'dodge': 7,
                     'ford': 8,
                     'gmc': 9,
                     'honda': 10,
                     'hyundai': 11,
                     'jeep': 12,
                     'kia': 13,
                     'lexus': 14,
                     'mazda': 15,
                     'nissan': 16,
                     'ram': 17,
                     'subaru': 18,
                     'toyota': 19,
                     'volkswagen': 20}
    
    condition_dict = {'excellent': 0, 'fair': 1, 'good': 2, 'like new': 3, 'new': 4, 'salvage': 5}
    cylinders_dict = {'10 cylinders': 0,
                     '12 cylinders': 1,
                     '3 cylinders': 2,
                     '4 cylinders': 3,
                     '5 cylinders': 4,
                     '6 cylinders': 5,
                     '8 cylinders': 6,
                     'other': 7}
    fuel_dict = {'diesel': 0, 'electric': 1, 'gas': 2, 'hybrid': 3, 'other': 4}
    transmission_dict = {'automatic': 0, 'manual': 1, 'other': 2}
    drive_dict = {'SUV': 0,
                 'bus': 1,
                 'convertible': 2,
                 'coupe': 3,
                 'hatchback': 4,
                 'mini-van': 5,
                 'offroad': 6,
                 'other': 7,
                 'pickup': 8,
                 'sedan': 9,
                 'truck': 10,
                 'van': 11,
                 'wagon': 12}
    cartype_dict = {'SUV': 0,
                     'bus': 1,
                     'convertible': 2,
                     'coupe': 3,
                     'hatchback': 4,
                     'mini-van': 5,
                     'offroad': 6,
                     'other': 7,
                     'pickup': 8,
                     'sedan': 9,
                     'truck': 10,
                     'van': 11,
                     'wagon': 12}
    paint_color_dict = {'black': 0,
                     'blue': 1,
                     'brown': 2,
                     'custom': 3,
                     'green': 4,
                     'grey': 5,
                     'orange': 6,
                     'purple': 7,
                     'red': 8,
                     'silver': 9,
                     'white': 10,
                     'yellow': 11}
    features = ['region', 'title_status', 'condition', 'age', 'manufacturer', 'model',
       'cylinders', 'fuel', 'odometer', 'transmission', 'drive', 'cartype',
       'paint_color', 'n_sold']
    
    #
    test_array = [region_dict[body.region],
                  title_status_dict[body.title_status],
                  condition_dict[body.condition],
                  body.age,
                  manufacturer_dic[body.manufacturer],
                  model_dict[body.model],
                  cylinders_dict[body.cylinders],
                  fuel_dict[body.fuel],
                  body.odometer,
                  transmission_dict[body.transmission],
                  drive_dict[body.drive],
                  cartype_dict[body.cartype],
                  paint_color_dict[body.paint_color],
                  body.n_sold]                                         

   
   
    test_array = np.array(test_array) # convert into numpy array
    
    test_array = test_array.reshape(1,-1) #reshape
    test_df = pd.DataFrame(test_array, columns = features)
    
    #declare path where you saved your model
    model_path = 'xgb_opt.pkl'
    #open file
    with open(model_path, "rb") as file:
        #load the trained model
        trained_model = joblib.load(file)

    return int(trained_model.predict(test_df))

     # import pdb;pdb.set_trace();